name: testing

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**.py'
      - 'tests/**.py'
      - '.github/testing.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**.py'
      - 'tests/**.py'
      - '.github/testing.yml'
  workflow_run:
    workflows:
      - 'pre-commit.ci'
    types:
      - completed

env:
  PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'poetry'
      - name: Install poetry dependencies
        run: poetry install --with dev
      - name: Run python tests
        run: poetry run pytest tests/